In [1]:
import pandas as pd

In [ ]:

orders = pd.read_csv("/home/tomas/Desktop/project-sales-analysis/data/raw/archive/olist_orders_dataset.csv")
order_items = pd.read_csv("/home/tomas/Desktop/project-sales-analysis/data/raw/archive/olist_order_items_dataset.csv")
customers = pd.read_csv("/home/tomas/Desktop/project-sales-analysis/data/raw/archive/olist_customers_dataset.csv")
payments = pd.read_csv("/home/tomas/Desktop/project-sales-analysis/data/raw/archive/olist_order_payments_dataset.csv")
reviews = pd.read_csv("/home/tomas/Desktop/project-sales-analysis/data/raw/archive/olist_order_reviews_dataset.csv")
products = pd.read_csv("/home/tomas/Desktop/project-sales-analysis/data/raw/archive/olist_products_dataset.csv")
sellers = pd.read_csv("/home/tomas/Desktop/project-sales-analysis/data/raw/archive/olist_sellers_dataset.csv")
geo = pd.read_csv("/home/tomas/Desktop/project-sales-analysis/data/raw/archive/olist_geolocation_dataset.csv")

In [5]:
# Unir ordenes con ítems
df = orders.merge(order_items, on="order_id", how="inner")

# Agregar clientes
df = df.merge(customers, on="customer_id", how="left")

# Agregar pagos
df = df.merge(payments, on="order_id", how="left")

# Agregar reviews
df = df.merge(reviews, on="order_id", how="left")

# Agregar productos
df = df.merge(products, on="product_id", how="left")

# Agregar vendedores
df = df.merge(sellers, on="seller_id", how="left")

In [11]:
df.head(5)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_item_id,product_id,...,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,seller_zip_code_prefix,seller_city,seller_state
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,1,87285b34884572647811a353c7ac498a,...,40.0,268.0,4.0,500.0,19.0,8.0,13.0,9350,maua,SP
1,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,1,87285b34884572647811a353c7ac498a,...,40.0,268.0,4.0,500.0,19.0,8.0,13.0,9350,maua,SP
2,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,1,87285b34884572647811a353c7ac498a,...,40.0,268.0,4.0,500.0,19.0,8.0,13.0,9350,maua,SP
3,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00,1,595fac2a385ac33a80bd5114aec74eb8,...,29.0,178.0,1.0,400.0,19.0,13.0,19.0,31570,belo horizonte,SP
4,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00,1,aa4383b373c6aca5d8797843e5594415,...,46.0,232.0,1.0,420.0,24.0,19.0,21.0,14840,guariba,SP

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 118310 entries, 0 to 118309
Data columns (total 39 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       118310 non-null  object
 1   customer_id                    118310 non-null  object
 2   order_status                   118310 non-null  object
 3   order_purchase_timestamp       118310 non-null  object
 4   order_approved_at              118295 non-null  object
 5   order_delivered_carrier_date   117056 non-null  object
 6   order_delivered_customer_date  115722 non-null  object
 7   order_estimated_delivery_date  118310 non-null  object
 8   order_item_id                  118310 non-null  int64
 9   product_id                     118310 non-null  object
 10  seller_id                      118310 non-null  object
 11  shipping_limit_date            118310 non-null  object
 12  price                          118310 non-null  float64
 13  freight_value                  118310 non-null  float64
 14  customer_unique_id             118310 non-null  object
 15  customer_zip_code_prefix       118310 non-null  int64
 16  customer_city                  118310 non-null  object
 17  customer_state                 118310 non-null  object
 18  payment_sequential             118307 non-null  float64
 19  payment_type                   118307 non-null  object
 20  payment_installments           118307 non-null  float64
 21  payment_value                  118307 non-null  float64
 22  review_id                      117332 non-null  object
 23  review_score                   117332 non-null  float64
 24  review_comment_title           13892 non-null   object
 25  review_comment_message         49682 non-null   object
 26  review_creation_date           117332 non-null  object
 27  review_answer_timestamp        117332 non-null  object
 28  product_category_name          116601 non-null  object
 29  product_name_lenght            116601 non-null  float64
 30  product_description_lenght     116601 non-null  float64
 31  product_photos_qty             116601 non-null  float64
 32  product_weight_g               118290 non-null  float64
 33  product_length_cm              118290 non-null  float64
 34  product_height_cm              118290 non-null  float64
 35  product_width_cm               118290 non-null  float64
 36  seller_zip_code_prefix         118310 non-null  int64
 37  seller_city                    118310 non-null  object
 38  seller_state                   118310 non-null  object
dtypes: float64(13), int64(3), object(23)
memory usage: 35.2+ MB

In [ ]:
#